// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrN-03ZEAg13NhGfchqwVw-M6WHzTTvZs',
    appId: '1:774371736276:web:90a207307af7a6da901941',
    messagingSenderId: '774371736276',
    projectId: 'tatafire-54c4a',
    authDomain: 'tatafire-54c4a.firebaseapp.com',
    storageBucket: 'tatafire-54c4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbBbXf8zLWyNyNd0T6P_yOP4Hvk30LT1c',
    appId: '1:774371736276:android:8a91bf52bd78fbdf901941',
    messagingSenderId: '774371736276',
    projectId: 'tatafire-54c4a',
    storageBucket: 'tatafire-54c4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUXoz8mrP_uv0ogNgs4el5wgnaoV7Nwhs',
    appId: '1:774371736276:ios:94df47bb310f31d2901941',
    messagingSenderId: '774371736276',
    projectId: 'tatafire-54c4a',
    storageBucket: 'tatafire-54c4a.appspot.com',
    iosBundleId: 'com.example.maindovre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUXoz8mrP_uv0ogNgs4el5wgnaoV7Nwhs',
    appId: '1:774371736276:ios:a8e0c5963b66a9d0901941',
    messagingSenderId: '774371736276',
    projectId: 'tatafire-54c4a',
    storageBucket: 'tatafire-54c4a.appspot.com',
    iosBundleId: 'com.example.maindovre.RunnerTests',
  );
}
